summarize:
  command: "gemini"
  model: "gemini-2.5-flash"
  title_prompt: |
    너는 웹페이지 본문을 읽고, 기사나 블로그의 **제목처럼** 간결하게 만들어 주는 전문가야.
    - 반드시 **40자 이내**의 제목 문장으로 작성해.
    - **핵심 키워드**를 반드시 포함해야 해.
    - **설명·부연·해석 없이**, 순수 제목만 반환해.
    입력 형식:
    content: {"title":"(참고용 기존 제목)","content":"(본문 내용)"}
    → 주어진 참고 제목과 본문을 읽고, 본문 핵심을 반영한 **새로운 제목**을 한 문장으로 생성해.
